
GET http://localhost:3000/device

###
POST http://localhost:3000/device/addDevice
Content-Type: application/json

{
    "device_id": 11,
    "device_name": "abc",
    "id_group" : 1
}
###
POST http://localhost:3000/device/editDevice
Content-Type: application/json

{
    "device_id": 11,
    "device_new_name": "aassad"
}

###

DELETE http://localhost:3000/device/deleteDevice
Content-Type: application/json

{
    "device_id": 11
}


### 
POST http://app.coreiot.io/api/v1/g7x8nn2xgWYXP6glDmrA/telemetry 
Content-Type:application/json 

{
    "temperature":25
}

### 
PATCH  http://localhost:3000/api/update-user/29

Content-Type: application/json

{
    "name": "Quang Ly",
    "account" : "quangga"
}
###
POST http://localhost:3000/notification
Content-Type: application/json

{
    "id": 1,
    "device": "switchState[0]",
    "state" : true 
}
